// This file is auto generated!
#ifndef __ETHA_IPSEC_REGS_H__
#define __ETHA_IPSEC_REGS_H__
#include <stdint.h>
#include <etha_ring_regs.h>


#define SEC_SESSION_SIZE 0x8
// macros: XFORM_CTX*
#define SEC_SESSION_CTX_OFFSET 0x0
// macros: KEY_VALUE*
#define SEC_SESSION_SALT_OFFSET 0x1
// macros: KEY_ADDRESS*
#define SEC_SESSION_CIPHER_KEY_LO_OFFSET 0x2
// macros: KEY_ADDRESS*
#define SEC_SESSION_CIPHER_KEY_HI_OFFSET 0x3
// macros: KEY_ADDRESS*
#define SEC_SESSION_HASH_KEY_LO_OFFSET 0x4
// macros: KEY_ADDRESS*
#define SEC_SESSION_HASH_KEY_HI_OFFSET 0x5


#define XFORM_CTX_VALID_POS 0
#define XFORM_CTX_VALID_FLAGS 0x1
//Enum: invalid : 0x0; valid : 0x1;
#define XFORM_CTX_VALID(x) (((x) >> XFORM_CTX_VALID_POS) & XFORM_CTX_VALID_FLAGS)
#define SET_XFORM_CTX_VALID(x) (((x) & XFORM_CTX_VALID_FLAGS) << XFORM_CTX_VALID_POS)


#define XFORM_CTX_CIPHER_ALG_POS 1
#define XFORM_CTX_CIPHER_ALG_FLAGS 0x3
//Enum: null : 0x0; aes_128 : 0x1; aes_256 : 0x2;
#define XFORM_CTX_CIPHER_ALG(x) (((x) >> XFORM_CTX_CIPHER_ALG_POS) & XFORM_CTX_CIPHER_ALG_FLAGS)
#define SET_XFORM_CTX_CIPHER_ALG(x) (((x) & XFORM_CTX_CIPHER_ALG_FLAGS) << XFORM_CTX_CIPHER_ALG_POS)


#define XFORM_CTX_CIPHER_MODE_POS 3
#define XFORM_CTX_CIPHER_MODE_FLAGS 0x3
//Enum: cbc : 0x0; ccm : 0x1; gcm : 0x2;
#define XFORM_CTX_CIPHER_MODE(x) (((x) >> XFORM_CTX_CIPHER_MODE_POS) & XFORM_CTX_CIPHER_MODE_FLAGS)
#define SET_XFORM_CTX_CIPHER_MODE(x) (((x) & XFORM_CTX_CIPHER_MODE_FLAGS) << XFORM_CTX_CIPHER_MODE_POS)


#define XFORM_CTX_HMAC_ALG_POS 5
#define XFORM_CTX_HMAC_ALG_FLAGS 0x3
//Enum: null : 0x0; sha1 : 0x1; sha256 : 0x2; sha512 : 0x3;
#define XFORM_CTX_HMAC_ALG(x) (((x) >> XFORM_CTX_HMAC_ALG_POS) & XFORM_CTX_HMAC_ALG_FLAGS)
#define SET_XFORM_CTX_HMAC_ALG(x) (((x) & XFORM_CTX_HMAC_ALG_FLAGS) << XFORM_CTX_HMAC_ALG_POS)


#define XFORM_CTX_SALT_LEN_POS 7
#define XFORM_CTX_SALT_LEN_FLAGS 0x7
#define XFORM_CTX_SALT_LEN(x) (((x) >> XFORM_CTX_SALT_LEN_POS) & XFORM_CTX_SALT_LEN_FLAGS)
#define SET_XFORM_CTX_SALT_LEN(x) (((x) & XFORM_CTX_SALT_LEN_FLAGS) << XFORM_CTX_SALT_LEN_POS)


#define XFORM_CTX_IV_LEN_POS 10
#define XFORM_CTX_IV_LEN_FLAGS 0x3f
#define XFORM_CTX_IV_LEN(x) (((x) >> XFORM_CTX_IV_LEN_POS) & XFORM_CTX_IV_LEN_FLAGS)
#define SET_XFORM_CTX_IV_LEN(x) (((x) & XFORM_CTX_IV_LEN_FLAGS) << XFORM_CTX_IV_LEN_POS)


#define XFORM_CTX_ICV_LEN_POS 16
#define XFORM_CTX_ICV_LEN_FLAGS 0xfff
#define XFORM_CTX_ICV_LEN(x) (((x) >> XFORM_CTX_ICV_LEN_POS) & XFORM_CTX_ICV_LEN_FLAGS)
#define SET_XFORM_CTX_ICV_LEN(x) (((x) & XFORM_CTX_ICV_LEN_FLAGS) << XFORM_CTX_ICV_LEN_POS)

#define SEC_SESSIONS_NUM 64
#define SEC_SESSION_OFFSET(base, name, i) ((base) + (SEC_SESSION_SIZE * i) + SEC_SESSION_##name##_OFFSET)
#define SEC_SESSIONS_OFFSET 0x0
#define QUEUE_NUM 4
#define QUEUE_REGS_OFFSET 0x800
#define RING(name, i) (QUEUE_REGS_OFFSET + (RING_REGS_SIZE * i) + RING_REGS_##name##_OFFSET)
#define SEC_SESSION(name, i) SEC_SESSION_OFFSET(SEC_SESSIONS_OFFSET, name, i)

#endif
