// This file is auto generated!
#ifndef __ETHA_REGS_H__
#define __ETHA_REGS_H__
#include <stdint.h>
#include <etha_ring_regs.h>

#define RX_REGS_OFFSET 0x0
#define TX_REGS_OFFSET 0x400
#define QUEUE_NUM 16
#define QUEUE_REGS_OFFSET 0x800
#define GLOBAL_REGS_OFFSET 0x1000

#define ETHA_GLOBAL_REGS_SIZE 0x400
// macros: ETHA_EN*
#define ETHA_GLOBAL_REGS_RX_EN_OFFSET 0x0
// macros: ETHA_EN*
#define ETHA_GLOBAL_REGS_TX_EN_OFFSET 0x1


#define ETHA_EN_EN_POS 0
#define ETHA_EN_EN_FLAGS 0x1
#define ETHA_EN_EN(x) (((x) >> ETHA_EN_EN_POS) & ETHA_EN_EN_FLAGS)
#define SET_ETHA_EN_EN(x) (((x) & ETHA_EN_EN_FLAGS) << ETHA_EN_EN_POS)

#define QUEUE_REGS_SIZE 0x20
#define RX_RINGS_OFFSET 0x0
#define TX_RINGS_OFFSET (RX_RINGS_OFFSET + RING_REGS_SIZE)
#define RX_RING_OFFSET(base, name, i) ((base) + (QUEUE_REGS_SIZE * i) + RX_RINGS_OFFSET + RING_REGS_##name##_OFFSET)
#define TX_RING_OFFSET(base, name, i) ((base) + (QUEUE_REGS_SIZE * i) + TX_RINGS_OFFSET + RING_REGS_##name##_OFFSET)

#define ETHER_TYPE_FILTER_REGS_SIZE 0x1
// macros: ETHER_TYPE_FILTER*
#define ETHER_TYPE_FILTER_REGS_ET_FILTER_OFFSET 0x0


#define ETHER_TYPE_FILTER_ETYPE_POS 0
#define ETHER_TYPE_FILTER_ETYPE_FLAGS 0xffff
#define ETHER_TYPE_FILTER_ETYPE(x) (((x) >> ETHER_TYPE_FILTER_ETYPE_POS) & ETHER_TYPE_FILTER_ETYPE_FLAGS)
#define SET_ETHER_TYPE_FILTER_ETYPE(x) (((x) & ETHER_TYPE_FILTER_ETYPE_FLAGS) << ETHER_TYPE_FILTER_ETYPE_POS)


#define ETHER_TYPE_FILTER_QUEUE_ID_POS 16
#define ETHER_TYPE_FILTER_QUEUE_ID_FLAGS 0xff
#define ETHER_TYPE_FILTER_QUEUE_ID(x) (((x) >> ETHER_TYPE_FILTER_QUEUE_ID_POS) & ETHER_TYPE_FILTER_QUEUE_ID_FLAGS)
#define SET_ETHER_TYPE_FILTER_QUEUE_ID(x) (((x) & ETHER_TYPE_FILTER_QUEUE_ID_FLAGS) << ETHER_TYPE_FILTER_QUEUE_ID_POS)


#define ETHER_TYPE_FILTER_CONGESTION_ACTION_POS 29
#define ETHER_TYPE_FILTER_CONGESTION_ACTION_FLAGS 0x3
//Enum: blocking : 0x0; drop : 0x1; default : 0x2;
#define ETHER_TYPE_FILTER_CONGESTION_ACTION(x) (((x) >> ETHER_TYPE_FILTER_CONGESTION_ACTION_POS) & ETHER_TYPE_FILTER_CONGESTION_ACTION_FLAGS)
#define SET_ETHER_TYPE_FILTER_CONGESTION_ACTION(x) (((x) & ETHER_TYPE_FILTER_CONGESTION_ACTION_FLAGS) << ETHER_TYPE_FILTER_CONGESTION_ACTION_POS)


#define ETHER_TYPE_FILTER_EN_POS 31
#define ETHER_TYPE_FILTER_EN_FLAGS 0x1
#define ETHER_TYPE_FILTER_EN(x) (((x) >> ETHER_TYPE_FILTER_EN_POS) & ETHER_TYPE_FILTER_EN_FLAGS)
#define SET_ETHER_TYPE_FILTER_EN(x) (((x) & ETHER_TYPE_FILTER_EN_FLAGS) << ETHER_TYPE_FILTER_EN_POS)


#define TUPLES_FILTER_REGS_SIZE 0x10
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_SRC_OFFSET 0x0
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_SRC_1_OFFSET 0x1
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_SRC_2_OFFSET 0x2
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_SRC_3_OFFSET 0x3
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_DST_OFFSET 0x4
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_DST_1_OFFSET 0x5
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_DST_2_OFFSET 0x6
// macros: TUPLES_FILTER_ADDRESS*
#define TUPLES_FILTER_REGS_TP5_V6_DST_3_OFFSET 0x7
// macros: TUPLES_FILTER_PORT*
#define TUPLES_FILTER_REGS_TP5_PORT_OFFSET 0x8
// macros: TUPLES_FILTER_CTRL*
#define TUPLES_FILTER_REGS_TP5_CTRL_OFFSET 0x9


#define TUPLES_FILTER_PORT_SRC_POS 0
#define TUPLES_FILTER_PORT_SRC_FLAGS 0xffff
#define TUPLES_FILTER_PORT_SRC(x) (((x) >> TUPLES_FILTER_PORT_SRC_POS) & TUPLES_FILTER_PORT_SRC_FLAGS)
#define SET_TUPLES_FILTER_PORT_SRC(x) (((x) & TUPLES_FILTER_PORT_SRC_FLAGS) << TUPLES_FILTER_PORT_SRC_POS)


#define TUPLES_FILTER_PORT_DST_POS 16
#define TUPLES_FILTER_PORT_DST_FLAGS 0xffff
#define TUPLES_FILTER_PORT_DST(x) (((x) >> TUPLES_FILTER_PORT_DST_POS) & TUPLES_FILTER_PORT_DST_FLAGS)
#define SET_TUPLES_FILTER_PORT_DST(x) (((x) & TUPLES_FILTER_PORT_DST_FLAGS) << TUPLES_FILTER_PORT_DST_POS)


#define TUPLES_FILTER_CTRL_PROTOCOL_POS 0
#define TUPLES_FILTER_CTRL_PROTOCOL_FLAGS 0xff
#define TUPLES_FILTER_CTRL_PROTOCOL(x) (((x) >> TUPLES_FILTER_CTRL_PROTOCOL_POS) & TUPLES_FILTER_CTRL_PROTOCOL_FLAGS)
#define SET_TUPLES_FILTER_CTRL_PROTOCOL(x) (((x) & TUPLES_FILTER_CTRL_PROTOCOL_FLAGS) << TUPLES_FILTER_CTRL_PROTOCOL_POS)


#define TUPLES_FILTER_CTRL_PRI_POS 8
#define TUPLES_FILTER_CTRL_PRI_FLAGS 0x7
#define TUPLES_FILTER_CTRL_PRI(x) (((x) >> TUPLES_FILTER_CTRL_PRI_POS) & TUPLES_FILTER_CTRL_PRI_FLAGS)
#define SET_TUPLES_FILTER_CTRL_PRI(x) (((x) & TUPLES_FILTER_CTRL_PRI_FLAGS) << TUPLES_FILTER_CTRL_PRI_POS)


#define TUPLES_FILTER_CTRL_IPV6_POS 11
#define TUPLES_FILTER_CTRL_IPV6_FLAGS 0x1
#define TUPLES_FILTER_CTRL_IPV6(x) (((x) >> TUPLES_FILTER_CTRL_IPV6_POS) & TUPLES_FILTER_CTRL_IPV6_FLAGS)
#define SET_TUPLES_FILTER_CTRL_IPV6(x) (((x) & TUPLES_FILTER_CTRL_IPV6_FLAGS) << TUPLES_FILTER_CTRL_IPV6_POS)


#define TUPLES_FILTER_CTRL_QUEUE_ID_POS 16
#define TUPLES_FILTER_CTRL_QUEUE_ID_FLAGS 0xff
#define TUPLES_FILTER_CTRL_QUEUE_ID(x) (((x) >> TUPLES_FILTER_CTRL_QUEUE_ID_POS) & TUPLES_FILTER_CTRL_QUEUE_ID_FLAGS)
#define SET_TUPLES_FILTER_CTRL_QUEUE_ID(x) (((x) & TUPLES_FILTER_CTRL_QUEUE_ID_FLAGS) << TUPLES_FILTER_CTRL_QUEUE_ID_POS)


#define TUPLES_FILTER_CTRL_SRC_MASK_POS 24
#define TUPLES_FILTER_CTRL_SRC_MASK_FLAGS 0x1
#define TUPLES_FILTER_CTRL_SRC_MASK(x) (((x) >> TUPLES_FILTER_CTRL_SRC_MASK_POS) & TUPLES_FILTER_CTRL_SRC_MASK_FLAGS)
#define SET_TUPLES_FILTER_CTRL_SRC_MASK(x) (((x) & TUPLES_FILTER_CTRL_SRC_MASK_FLAGS) << TUPLES_FILTER_CTRL_SRC_MASK_POS)


#define TUPLES_FILTER_CTRL_DST_MASK_POS 25
#define TUPLES_FILTER_CTRL_DST_MASK_FLAGS 0x1
#define TUPLES_FILTER_CTRL_DST_MASK(x) (((x) >> TUPLES_FILTER_CTRL_DST_MASK_POS) & TUPLES_FILTER_CTRL_DST_MASK_FLAGS)
#define SET_TUPLES_FILTER_CTRL_DST_MASK(x) (((x) & TUPLES_FILTER_CTRL_DST_MASK_FLAGS) << TUPLES_FILTER_CTRL_DST_MASK_POS)


#define TUPLES_FILTER_CTRL_PROTOCOL_MASK_POS 26
#define TUPLES_FILTER_CTRL_PROTOCOL_MASK_FLAGS 0x1
#define TUPLES_FILTER_CTRL_PROTOCOL_MASK(x) (((x) >> TUPLES_FILTER_CTRL_PROTOCOL_MASK_POS) & TUPLES_FILTER_CTRL_PROTOCOL_MASK_FLAGS)
#define SET_TUPLES_FILTER_CTRL_PROTOCOL_MASK(x) (((x) & TUPLES_FILTER_CTRL_PROTOCOL_MASK_FLAGS) << TUPLES_FILTER_CTRL_PROTOCOL_MASK_POS)


#define TUPLES_FILTER_CTRL_SRC_PORT_MASK_POS 27
#define TUPLES_FILTER_CTRL_SRC_PORT_MASK_FLAGS 0x1
#define TUPLES_FILTER_CTRL_SRC_PORT_MASK(x) (((x) >> TUPLES_FILTER_CTRL_SRC_PORT_MASK_POS) & TUPLES_FILTER_CTRL_SRC_PORT_MASK_FLAGS)
#define SET_TUPLES_FILTER_CTRL_SRC_PORT_MASK(x) (((x) & TUPLES_FILTER_CTRL_SRC_PORT_MASK_FLAGS) << TUPLES_FILTER_CTRL_SRC_PORT_MASK_POS)


#define TUPLES_FILTER_CTRL_DST_PORT_MASK_POS 28
#define TUPLES_FILTER_CTRL_DST_PORT_MASK_FLAGS 0x1
#define TUPLES_FILTER_CTRL_DST_PORT_MASK(x) (((x) >> TUPLES_FILTER_CTRL_DST_PORT_MASK_POS) & TUPLES_FILTER_CTRL_DST_PORT_MASK_FLAGS)
#define SET_TUPLES_FILTER_CTRL_DST_PORT_MASK(x) (((x) & TUPLES_FILTER_CTRL_DST_PORT_MASK_FLAGS) << TUPLES_FILTER_CTRL_DST_PORT_MASK_POS)


#define TUPLES_FILTER_CTRL_CONGESTION_ACTION_POS 29
#define TUPLES_FILTER_CTRL_CONGESTION_ACTION_FLAGS 0x3
//Enum: blocking : 0x0; drop : 0x1; default : 0x2;
#define TUPLES_FILTER_CTRL_CONGESTION_ACTION(x) (((x) >> TUPLES_FILTER_CTRL_CONGESTION_ACTION_POS) & TUPLES_FILTER_CTRL_CONGESTION_ACTION_FLAGS)
#define SET_TUPLES_FILTER_CTRL_CONGESTION_ACTION(x) (((x) & TUPLES_FILTER_CTRL_CONGESTION_ACTION_FLAGS) << TUPLES_FILTER_CTRL_CONGESTION_ACTION_POS)


#define TUPLES_FILTER_CTRL_EN_POS 31
#define TUPLES_FILTER_CTRL_EN_FLAGS 0x1
#define TUPLES_FILTER_CTRL_EN(x) (((x) >> TUPLES_FILTER_CTRL_EN_POS) & TUPLES_FILTER_CTRL_EN_FLAGS)
#define SET_TUPLES_FILTER_CTRL_EN(x) (((x) & TUPLES_FILTER_CTRL_EN_FLAGS) << TUPLES_FILTER_CTRL_EN_POS)

#define TP5_FILTERS_NUM 16
#define TP5_FILTERS_OFFSET 0x0
#define ET_FILTERS_NUM 4
#define ET_FILTERS_OFFSET 0x200
#define TP5_FILTER_OFFSET(base, name, i) ((base) + TP5_FILTERS_OFFSET + (TUPLES_FILETER_REGS_SIZE * i) + TUPLES_FILTER_REGS_##name##_OFFSET)
#define ET_FILTER_OFFSET(base, i) ((base) + ET_FILTERS_OFFSET + (ETHER_TYPE_FILTER_REGS_SIZE * i))

#define DEFAULT_FILTER_REGS_SIZE 0x1
// macros: DEFAULT_QUEUE*
#define DEFAULT_FILTER_REGS_DEFAULT_Q_OFFSET 0x0


#define DEFAULT_QUEUE_QUEUE_ID_POS 16
#define DEFAULT_QUEUE_QUEUE_ID_FLAGS 0xff
#define DEFAULT_QUEUE_QUEUE_ID(x) (((x) >> DEFAULT_QUEUE_QUEUE_ID_POS) & DEFAULT_QUEUE_QUEUE_ID_FLAGS)
#define SET_DEFAULT_QUEUE_QUEUE_ID(x) (((x) & DEFAULT_QUEUE_QUEUE_ID_FLAGS) << DEFAULT_QUEUE_QUEUE_ID_POS)


#define DEFAULT_QUEUE_CONGESTION_ACTION_POS 29
#define DEFAULT_QUEUE_CONGESTION_ACTION_FLAGS 0x1
//Enum: blocking : 0x0; drop : 0x1;
#define DEFAULT_QUEUE_CONGESTION_ACTION(x) (((x) >> DEFAULT_QUEUE_CONGESTION_ACTION_POS) & DEFAULT_QUEUE_CONGESTION_ACTION_FLAGS)
#define SET_DEFAULT_QUEUE_CONGESTION_ACTION(x) (((x) & DEFAULT_QUEUE_CONGESTION_ACTION_FLAGS) << DEFAULT_QUEUE_CONGESTION_ACTION_POS)


#define DEFAULT_QUEUE_EN_POS 31
#define DEFAULT_QUEUE_EN_FLAGS 0x1
#define DEFAULT_QUEUE_EN(x) (((x) >> DEFAULT_QUEUE_EN_POS) & DEFAULT_QUEUE_EN_FLAGS)
#define SET_DEFAULT_QUEUE_EN(x) (((x) & DEFAULT_QUEUE_EN_FLAGS) << DEFAULT_QUEUE_EN_POS)

#define DEFAULT_Q_OFFSET(base) ((base) + 0x204)
#define TP5_FILTER(name, i) TP5_FILTER_OFFSET(RX_REGS_OFFSET, name, i)
#define ET_FILTER(i) ET_FILTER_OFFSET(RX_REGS_OFFSET, i)
#define DEFAULT_Q DEFAULT_Q_OFFSET(RX_REGS_OFFSET)
#define RX_RING(name, i) RX_RING_OFFSET(QUEUE_REGS_OFFSET, name, i)
#define TX_RING(name, i) TX_RING_OFFSET(QUEUE_REGS_OFFSET, name, i)
#define RX_EN (GLOBAL_REGS_OFFSET + ETHA_GLOBAL_REGS_RX_EN_OFFSET)
#define TX_EN (GLOBAL_REGS_OFFSET + ETHA_GLOBAL_REGS_TX_EN_OFFSET)

#endif
