// This file is auto generated!
#ifndef __ETHA_RING_REGS_H__
#define __ETHA_RING_REGS_H__
#include <stdint.h>
#define RING_REGS_SIZE 0x10


#define RING_REGS_SIZE 0x10
// macros: RING_BASE*
#define RING_REGS_REQ_BASE_L_OFFSET 0x0
// macros: RING_BASE*
#define RING_REGS_REQ_BASE_H_OFFSET 0x1
// macros: RING_BASE*
#define RING_REGS_RESP_BASE_L_OFFSET 0x2
// macros: RING_BASE*
#define RING_REGS_RESP_BASE_H_OFFSET 0x3
// macros: RING_SIZE*
#define RING_REGS_SIZE_OFFSET 0x4
// macros: RING_SIZE*
#define RING_REGS_H_WATER_MARK_OFFSET 0x5
// macros: RING_SIZE*
#define RING_REGS_L_WATER_MARK_OFFSET 0x6
// macros: RING_PTR*
#define RING_REGS_P_CONSUMER_OFFSET 0x7
// macros: RING_PTR*
#define RING_REGS_P_PRODUCER_OFFSET 0x8
// macros: RING_STATUS*
#define RING_REGS_STATUS_OFFSET 0x9
// macros: RING_STATUS*
#define RING_REGS_INT_MASK_OFFSET 0xa
// macros: RING_CTRL*
#define RING_REGS_CTRL_OFFSET 0xc
// macros: RING_SIZE*
#define RING_REGS_MEM_SIZE_OFFSET 0xd




#define RING_SIZE_SIZE_POS 0
#define RING_SIZE_SIZE_FLAGS 0x7fffffff
#define RING_SIZE_SIZE(x) (((x) >> RING_SIZE_SIZE_POS) & RING_SIZE_SIZE_FLAGS)
#define SET_RING_SIZE_SIZE(x) (((x) & RING_SIZE_SIZE_FLAGS) << RING_SIZE_SIZE_POS)




#define RING_PTR_PTR_POS 0
#define RING_PTR_PTR_FLAGS 0x7fffffff
#define RING_PTR_PTR(x) (((x) >> RING_PTR_PTR_POS) & RING_PTR_PTR_FLAGS)
#define SET_RING_PTR_PTR(x) (((x) & RING_PTR_PTR_FLAGS) << RING_PTR_PTR_POS)


#define RING_PTR_ROUND_POS 31
#define RING_PTR_ROUND_FLAGS 0x1
#define RING_PTR_ROUND(x) (((x) >> RING_PTR_ROUND_POS) & RING_PTR_ROUND_FLAGS)
#define SET_RING_PTR_ROUND(x) (((x) & RING_PTR_ROUND_FLAGS) << RING_PTR_ROUND_POS)




#define RING_STATUS_FULL_POS 0
#define RING_STATUS_FULL_FLAGS 0x1
#define RING_STATUS_FULL(x) (((x) >> RING_STATUS_FULL_POS) & RING_STATUS_FULL_FLAGS)
#define SET_RING_STATUS_FULL(x) (((x) & RING_STATUS_FULL_FLAGS) << RING_STATUS_FULL_POS)


#define RING_STATUS_EMPTY_POS 1
#define RING_STATUS_EMPTY_FLAGS 0x1
#define RING_STATUS_EMPTY(x) (((x) >> RING_STATUS_EMPTY_POS) & RING_STATUS_EMPTY_FLAGS)
#define SET_RING_STATUS_EMPTY(x) (((x) & RING_STATUS_EMPTY_FLAGS) << RING_STATUS_EMPTY_POS)


#define RING_STATUS_ALMOST_FULL_POS 2
#define RING_STATUS_ALMOST_FULL_FLAGS 0x1
#define RING_STATUS_ALMOST_FULL(x) (((x) >> RING_STATUS_ALMOST_FULL_POS) & RING_STATUS_ALMOST_FULL_FLAGS)
#define SET_RING_STATUS_ALMOST_FULL(x) (((x) & RING_STATUS_ALMOST_FULL_FLAGS) << RING_STATUS_ALMOST_FULL_POS)


#define RING_STATUS_ALMOST_EMPTY_POS 3
#define RING_STATUS_ALMOST_EMPTY_FLAGS 0x1
#define RING_STATUS_ALMOST_EMPTY(x) (((x) >> RING_STATUS_ALMOST_EMPTY_POS) & RING_STATUS_ALMOST_EMPTY_FLAGS)
#define SET_RING_STATUS_ALMOST_EMPTY(x) (((x) & RING_STATUS_ALMOST_EMPTY_FLAGS) << RING_STATUS_ALMOST_EMPTY_POS)




#define RING_CTRL_ENABLE_POS 0
#define RING_CTRL_ENABLE_FLAGS 0x1
#define RING_CTRL_ENABLE(x) (((x) >> RING_CTRL_ENABLE_POS) & RING_CTRL_ENABLE_FLAGS)
#define SET_RING_CTRL_ENABLE(x) (((x) & RING_CTRL_ENABLE_FLAGS) << RING_CTRL_ENABLE_POS)


#endif
